name: async_periodic_observable
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Federico Violante <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  rxdart: ^0.19.0

dev_dependencies:
  test: ^1.0.0
